import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {PGlite} from '@electric-sql/pglite';
const sid='11111111-1111-4111-8111-111111111111',uid='22222222-2222-4222-8222-222222222222',cat='33333333-3333-4333-8333-333333333333',size='44444444-4444-4444-8444-444444444444',pid='55555555-5555-4555-8555-555555555555',off='66666666-6666-4666-8666-666666666666';
const migration=fs.readFileSync('supabase/migrations/20261007113743_achado4_catalog_compatibility.sql','utf8')+'\n'+fs.readFileSync('supabase/migrations/20261007113745_achado4_catalog_enforcement.sql','utf8');
test('real local PostgreSQL: atomic RPC, direct writes, RLS and legacy preservation',async t=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema private;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table stores(id uuid primary key,owner_id uuid);create table categories(id uuid primary key,store_id uuid);
 create table products(id uuid primary key default gen_random_uuid(),store_id uuid not null references stores,category_id uuid not null references categories,name text not null,description text,image_url text,codigo integer,is_pizza boolean not null,available boolean not null,has_crusts boolean not null default false,has_extras boolean not null default false,is_featured boolean not null default false,featured_order integer not null default 0,base_price numeric not null);
 create table pizza_sizes(id uuid primary key,store_id uuid not null references stores,is_active boolean not null);
 create table product_size_prices(product_id uuid references products on delete cascade,size_id uuid references pizza_sizes on delete cascade,price numeric not null,primary key(product_id,size_id));
 create function private.member_store(sid uuid) returns boolean language sql security definer set search_path='' as $$select exists(select 1 from public.stores where id=sid and owner_id=auth.uid())$$;
 grant usage on schema public,auth,private to authenticated,anon;
 grant select on stores,categories to authenticated;
 grant select,insert,update,delete on products,pizza_sizes,product_size_prices to authenticated;
 alter table products enable row level security;alter table pizza_sizes enable row level security;alter table product_size_prices enable row level security;
 create policy member on products for all to authenticated using(private.member_store(store_id)) with check(private.member_store(store_id));
 create policy member on pizza_sizes for all to authenticated using(private.member_store(store_id)) with check(private.member_store(store_id));
 create policy member on product_size_prices for all to authenticated using(exists(select 1 from products p join pizza_sizes s on s.store_id=p.store_id where p.id=product_id and s.id=size_id and private.member_store(p.store_id))) with check(exists(select 1 from products p join pizza_sizes s on s.store_id=p.store_id where p.id=product_id and s.id=size_id and private.member_store(p.store_id)));
 insert into stores values('${sid}','${uid}');insert into categories values('${cat}','${sid}');
 insert into pizza_sizes values('${size}','${sid}',true),('${off}','${sid}',false);
 insert into products(id,store_id,category_id,name,base_price,is_pizza,available) select gen_random_uuid(),'${sid}','${cat}','Legacy '||n,0,true,true from generate_series(1,37) n;
 `);
 const before=await db.query("select jsonb_agg(p order by id) rows from products p");await db.exec(migration);
 await t.test('37 synthetic legacy rows unchanged by migration',async()=>assert.deepEqual(await db.query('select jsonb_agg(p order by id) rows from products p'),before));
 const data={name:'Valid',category_id:cat,codigo:101,is_pizza:true,available:true,has_crusts:true,has_extras:true,is_featured:false,featured_order:0,base_price:0};
 const rpc=async(id,prices,patch={})=>db.query('select (public.save_product_with_prices($1,$2,$3,$4)).id',[sid,id,{...data,...patch},prices]);
 const login=()=>db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${uid}',false);`);
 await login();
 const fails=async fn=>{await assert.rejects(fn);};
 await t.test('available without price rejected and product rolled back',async()=>{const n=(await db.query('select count(*) n from products')).rows[0].n;await fails(()=>rpc(null,[]));assert.equal((await db.query('select count(*) n from products')).rows[0].n,n);});
 await t.test('inactive-only rejected',async()=>fails(()=>rpc(null,[{size_id:off,price:60}])));
 await t.test('unavailable without price allowed',async()=>{await rpc(pid,[]).catch(()=>{});const r=await rpc(null,[],{available:false});assert.ok(r.rows[0].id);});
 let validId;
 await t.test('one active price accepted',async()=>{validId=(await rpc(null,[{size_id:size,price:60}])).rows[0].id;});
 await t.test('two prices and atomic replacement accepted',async()=>{await rpc(validId,[{size_id:size,price:65},{size_id:off,price:70}]);assert.equal((await db.query('select count(*) n from product_size_prices where product_id=$1',[validId])).rows[0].n,2);});
 await t.test('delete last active price directly rejected',async()=>fails(()=>db.query('delete from product_size_prices where product_id=$1 and size_id=$2',[validId,size])));
 for(const value of ['0','-1',"'NaN'","'Infinity'","'-Infinity'",'null'])await t.test('direct invalid price '+value,async()=>fails(()=>db.exec(`update product_size_prices set price=${value} where product_id='${validId}' and size_id='${size}'`)));
 await t.test('deactivate last usable size rejected',async()=>fails(()=>db.exec(`update pizza_sizes set is_active=false where id='${size}'`)));
 await t.test('delete last usable size rejected',async()=>fails(()=>db.exec(`delete from pizza_sizes where id='${size}'`)));
 await t.test('direct available product insert rejected',async()=>fails(()=>db.exec(`insert into products(store_id,category_id,name,base_price,is_pizza,available) values('${sid}','${cat}','Bypass',0,true,true)`)));
 await t.test('late failure rolls back product and all prices',async()=>{const old=await db.query('select to_jsonb(p) p from products p where id=$1',[validId]);const prices=await db.query('select * from product_size_prices where product_id=$1 order by size_id',[validId]);await fails(()=>rpc(validId,[{size_id:size,price:99},{size_id:'99999999-9999-4999-8999-999999999999',price:10}],{name:'Should rollback'}));assert.deepEqual(await db.query('select to_jsonb(p) p from products p where id=$1',[validId]),old);assert.deepEqual(await db.query('select * from product_size_prices where product_id=$1 order by size_id',[validId]),prices);});
 await t.test('ordinary product preserved',async()=>assert.ok((await rpc(null,[],{is_pizza:false,base_price:10})).rows[0].id));
 await t.test('other owner cannot use RPC',async()=>{await db.exec("select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999999',false)");await fails(()=>rpc(validId,[{size_id:size,price:1}]));await login();});
 await t.test('anon cannot call RPC',async()=>{await db.exec('reset role;set role anon');await fails(()=>rpc(null,[]));await db.exec('reset role');await login();});
 await t.test('private guard unavailable to authenticated',async()=>fails(()=>db.exec('delete from private.catalog_write_guard')));
 await t.test('legacy edit must resolve invalidity or pause',async()=>{const legacy=(await db.query("select id from products where name='Legacy 1'")).rows[0].id;await fails(()=>db.query("update products set name='Still invalid' where id=$1",[legacy]));await db.query('update products set available=false where id=$1',[legacy]);});
 }finally{await db.close();}
});
